export const REDUX_ACTION_API_CALL = 'REDUX_ACTION_API_CALL';
export const REDUX_ACTION_PAGINATION_LOADING = 'REDUX_ACTION_PAGINATION_LOADING';
export const REDUX_ACTION_SET_PEOPLE = 'REDUX_ACTION_SET_PEOPLE';
export const SET_CONTACTS_PAGINATION = 'SET_CONTACTS_PAGINATION';